apiVersion: apps/v1
kind: Deployment
metadata:
  name: microinteressado-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: microinteressado
  replicas: 2
  template:
    metadata:
      labels:
        app: microinteressado
    spec:
        containers:
          - name: microinteressado
            image: gcr.io/projetoptiptr-307918/microinteressado:v1

--- 
#Service
apiVersion: v1
kind: Service
metadata:
  name: microinteressado-service
spec:
  selector:
    app: microinteressado
  type: ClusterIP
  ports:
    - name: http
      port: 8082